name: web_docs

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Build website
        run: npm run docs:build

      - name: web_docs
        uses: JamesIves/github-pages-deploy-action@4.1.3
        with:
          branch: gh-pages
          folder: docs/.vitepress/dist
          token: ${{ secrets.WEB_DOCS }}
      - name: Debug
        run: |
          env
          git config --global user.name "Your Name"
          git config --global user.email "youremail@example.com"
          git remote -v
          git branch -a
